apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: churnguard-api
  namespace: churnguard
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: churnguard.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: churnguard-api
                port:
                  number: 80
